
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solana-sign-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solana-sign-service
  template:
    metadata:
      labels:
        app: solana-sign-service
    spec:
      containers:
      - name: solana-sign-service
        image: ${CONTAINER_REGISTRY}/solana-sign-service:${IMAGE_TAG}
        env:
            - name: DATABASE_HOST
              value: "57.151.72.86"
            - name: DATABASE_NAME
              value: dashboard_prod
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: SIGNATURE_SERVICE
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "80"
            - name: DB_ADMIN_PUBLIC_KEY
              value: NFNDevuQj3z4uMNN86k2PgnbGWdpoApbXwtTMY6B99F
            - name: SOLANA_API_URL
              value: https://mainnet.helius-rpc.com/
            - name: DEFAULT_REWARD_TOKEN_MINT
              value: WAYRUy2VkqUCBg49sUSmJ2wYHzWpVjokZfQiGzdrAV3
            - name: DEFAULT_REWARD_SYSTEM_PROGRAM_ID
              value: EqeqjHyJTsmnVFCs3rnUEKSgvYBtjXa5ujJueiexWLHp
            - name: DEFAULT_AIRDROPS_PROGRAM_ID
              value: 9xQcf54GAkeU8pGPoE7A6twxcBgWjUsARCzBfEXHEq7S
            - name: DEFAULT_STAKE_SYSTEM_PROGRAM_ID
              value: 2W41afA7PC45mmmbDfsBanKr2s4ac8EPJLrL1DKdxLj9
            - name: ADMIN_REWARD_SYSTEM_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: signature-service-secrets
                  key: ADMIN_REWARD_SYSTEM_PRIVATE_KEY
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: signature-service-secrets
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: signature-service-secrets
                  key: JWT_SECRET
            - name: SOLANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: signature-service-secrets
                  key: SOLANA_API_KEY
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
