apiVersion: v1
kind: Secret
metadata:
  name: signature-service-secrets
data:
  ADMIN_REWARD_SYSTEM_PRIVATE_KEY: KytrTFJHPS5NbS1HbS5NbS1H5NbS1HbQ==
  DATABASE_PASSWORD: KytrTFJHPS5NbS1HbS5NbS1H5NbS1HbQ==
  JWT_SECRET: KytrTFJHPS5NbS1HbS5NbS1H5NbS1HbQ==
---   