
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solana-sign-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solana-sign-service
  template:
    metadata:
      labels:
        app: solana-sign-service
    spec:
      containers:
      - name: solana-sign-service
        image: ${CONTAINER_REGISTRY}/solana-sign-service:${IMAGE_TAG}
        env:
            - name: DATABASE_HOST
              value: "172.168.206.66"
            - name: DATABASE_NAME
              value: dashboard_prod_test
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: SIGNATURE_SERVICE
            - name: NODE_ENV
              value: develop
            - name: PORT
              value: "80"
            - name: DB_ADMIN_PUBLIC_KEY
              value: 8QMK1JHzjydq7qHgTo1RwK3ateLm4zVQF7V7BkriNkeD
            - name: SOLANA_API_URL
              value: https://devnet.helius-rpc.com/
            - name: DEFAULT_REWARD_TOKEN_MINT
              value: CyVfcAhqHoY28roieSxAx9B4RCcGEDnVrxbwoc3oH7wa
            - name: DEFAULT_REWARD_SYSTEM_PROGRAM_ID
              value: DGkrN8CiTvRSZbqa7rZjKJ5SHEmMm9Q7JMDjKubidhtV
            - name: DEFAULT_AIRDROPS_PROGRAM_ID
              value: 5KK2ThgEp1AZM8bo79ijJcumSqz9B48bszyhYhuw3K7o
            - name: ADMIN_REWARD_SYSTEM_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: signature-service-secrets
                  key: ADMIN_REWARD_SYSTEM_PRIVATE_KEY
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: signature-service-secrets
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: signature-service-secrets
                  key: JWT_SECRET
            - name: SOLANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: signature-service-secrets
                  key: SOLANA_API_KEY
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
