apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solana-sign-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
    kubernetes.io/ingress.class: "nginx"  
spec:
  rules:
  - host: secrets.dev.wayru.tech  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: solana-sign-service  
            port:
              number: 80  
